#!/bin/dash

if [ "$PPP_IFACE" = "ppp0" ]; then
    ip route add 10.89.23.0/24 dev ppp0
    # Using a network configuration file and KeepConfiguration=static
    # seems to be not working or at least issue prone in some cases:
    # https://github.com/systemd/systemd/issues/14255
    # https://github.com/systemd/systemd/issues/26356
    resolvectl dns ppp0 10.89.23.40 10.89.23.41
fi
